other:
    username: ${spring.datasource.username}

spring:
    datasource:
        url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: to-be-overwritten-by-vault-value
        password: to-be-overwritten-by-vault-value
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect